-- MySQL Script generated by MySQL Workbench
-- vie 13 nov 2020 21:30:51 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONA` (
  `Nombre_Zona` VARCHAR(45) NOT NULL,
  `Ubicación` VARCHAR(45) NULL,
  `Concejal` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre_Zona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BLOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BLOQUE` (
  `Número_Bloque` INT NOT NULL,
  `Calle_Bloque` VARCHAR(45) NOT NULL,
  `Año_Construcción` INT NULL,
  `Superficie` FLOAT NULL,
  `Número_Habitantes` INT NULL,
  `Nombre_Zona` VARCHAR(45) NULL,
  PRIMARY KEY (`Número_Bloque`, `Calle_Bloque`),
  INDEX `Nombre_Zona_FK_idx` (`Nombre_Zona` ASC) VISIBLE,
  CONSTRAINT `Nombre_Zona_FK`
    FOREIGN KEY (`Nombre_Zona`)
    REFERENCES `mydb`.`ZONA` (`Nombre_Zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UNIFAMILIAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UNIFAMILIAR` (
  `Número_Unifamiliar` INT NOT NULL,
  `Calle_Unifamiliar` VARCHAR(45) NOT NULL,
  `Año_Construcción` INT NULL,
  `Superficie` FLOAT NULL,
  `Número_Habitantes` INT NULL,
  `Nombre_Zona` VARCHAR(45) NULL,
  PRIMARY KEY (`Número_Unifamiliar`, `Calle_Unifamiliar`),
  INDEX `Nombre_Zona_FK_idx` (`Nombre_Zona` ASC) VISIBLE,
  CONSTRAINT `Nombre_Zona_FK`
    FOREIGN KEY (`Nombre_Zona`)
    REFERENCES `mydb`.`ZONA` (`Nombre_Zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PISO` (
  `Piso_Número_Piso` INT NOT NULL,
  `Letra_Piso` VARCHAR(1) NOT NULL,
  `Número_Bloque` INT NOT NULL,
  `Calle_Bloque` VARCHAR(45) NOT NULL,
  `Número_Habitantes` VARCHAR(45) NULL,
  PRIMARY KEY (`Piso_Número_Piso`, `Letra_Piso`, `Calle_Bloque`, `Número_Bloque`),
  INDEX `Número_idx` (`Número_Bloque` ASC, `Calle_Bloque` ASC) VISIBLE,
  CONSTRAINT `FK`
    FOREIGN KEY (`Número_Bloque` , `Calle_Bloque`)
    REFERENCES `mydb`.`BLOQUE` (`Número_Bloque` , `Calle_Bloque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA` (
  `DNI` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Teléfono` INT NULL,
  `Número_Unifamiliar` INT NOT NULL,
  `Calle_Unifamiliar` VARCHAR(45) NOT NULL,
  `Piso_Número_Piso` INT NOT NULL,
  `Letra_Piso` VARCHAR(1) NOT NULL,
  `Número_Bloque` INT NOT NULL,
  `Calle_Bloque` VARCHAR(45) NOT NULL,
  `Cabeza_Familia` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`),
  INDEX `Número_Unifamiliar_idx` (`Número_Unifamiliar` ASC, `Calle_Unifamiliar` ASC) VISIBLE,
  INDEX `Piso_Número_Piso_idx` (`Piso_Número_Piso` ASC, `Letra_Piso` ASC, `Número_Bloque` ASC, `Calle_Bloque` ASC) VISIBLE,
  INDEX `Cabeza_Familia_idx` (`Cabeza_Familia` ASC) VISIBLE,
  CONSTRAINT `FK1`
    FOREIGN KEY (`Número_Unifamiliar` , `Calle_Unifamiliar`)
    REFERENCES `mydb`.`UNIFAMILIAR` (`Número_Unifamiliar` , `Calle_Unifamiliar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK2`
    FOREIGN KEY (`Piso_Número_Piso` , `Letra_Piso` , `Número_Bloque` , `Calle_Bloque`)
    REFERENCES `mydb`.`PISO` (`Piso_Número_Piso` , `Letra_Piso` , `Número_Bloque` , `Calle_Bloque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK3`
    FOREIGN KEY (`Cabeza_Familia`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONA-POSEE-UNIFAMILIAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA-POSEE-UNIFAMILIAR` (
  `DNI` VARCHAR(10) NOT NULL,
  `Número_Unifamiliar` INT NOT NULL,
  `Calle_Unifamiliar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`, `Número_Unifamiliar`, `Calle_Unifamiliar`),
  INDEX `Número_Unifamiliar_idx` (`Número_Unifamiliar` ASC, `Calle_Unifamiliar` ASC) VISIBLE,
  CONSTRAINT `FK1`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK2`
    FOREIGN KEY (`Número_Unifamiliar` , `Calle_Unifamiliar`)
    REFERENCES `mydb`.`UNIFAMILIAR` (`Número_Unifamiliar` , `Calle_Unifamiliar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONA-POSEE-PISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA-POSEE-PISO` (
  `DNI` VARCHAR(10) NOT NULL,
  `Piso_Número_Piso` INT NOT NULL,
  `Letra_Piso` VARCHAR(1) NOT NULL,
  `Número_Bloque` INT NOT NULL,
  `Calle_Bloque` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`, `Piso_Número_Piso`, `Letra_Piso`, `Número_Bloque`, `Calle_Bloque`),
  INDEX `Piso_Número_Piso_idx` (`Piso_Número_Piso` ASC, `Letra_Piso` ASC, `Número_Bloque` ASC, `Calle_Bloque` ASC) VISIBLE,
  CONSTRAINT `FK1`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK2`
    FOREIGN KEY (`Piso_Número_Piso` , `Letra_Piso` , `Número_Bloque` , `Calle_Bloque`)
    REFERENCES `mydb`.`PISO` (`Piso_Número_Piso` , `Letra_Piso` , `Número_Bloque` , `Calle_Bloque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
