-- MySQL Script generated by MySQL Workbench
-- vie 13 nov 2020 22:06:17 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`VIVERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIVERO` (
  `Ubicacion` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Hora_Apertura` VARCHAR(45) NULL,
  `Hora_Cierre` VARCHAR(45) NULL,
  PRIMARY KEY (`Ubicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZONAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONAS` (
  `Cod_Zona` INT NOT NULL,
  `Ubicacion` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Cod_Zona`),
  INDEX `FK_idx` (`Ubicacion` ASC) VISIBLE,
  CONSTRAINT `FK`
    FOREIGN KEY (`Ubicacion`)
    REFERENCES `mydb`.`VIVERO` (`Ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `DNI_Empleado` VARCHAR(10) NOT NULL,
  `Seguridad_Social` VARCHAR(45) NOT NULL,
  `Nombre_Completo` VARCHAR(45) NULL,
  `Sueldo` INT NULL,
  PRIMARY KEY (`DNI_Empleado`, `Seguridad_Social`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO` (
  `Codigo_Barras` INT NOT NULL,
  `Nombre_Producto` VARCHAR(45) NULL,
  `Tipo_Producto` VARCHAR(45) NULL,
  `Precio` FLOAT NULL,
  `Stock` INT NULL,
  `Fecha_Caducidad` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_Barras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO-ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO-ZONA` (
  `DNI_Empleado` VARCHAR(10) NOT NULL,
  `Fecha_Inicio` VARCHAR(45) NOT NULL,
  `Cod_Zona` INT NULL,
  PRIMARY KEY (`DNI_Empleado`, `Fecha_Inicio`),
  INDEX `FK2_idx` (`Cod_Zona` ASC) VISIBLE,
  CONSTRAINT `FK1`
    FOREIGN KEY (`DNI_Empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`DNI_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK2`
    FOREIGN KEY (`Cod_Zona`)
    REFERENCES `mydb`.`ZONAS` (`Cod_Zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZONA-PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONA-PRODUCTO` (
  `Cod_Zona` INT NOT NULL,
  `Codigo_Barras` INT NOT NULL,
  PRIMARY KEY (`Cod_Zona`, `Codigo_Barras`),
  INDEX `FK2_idx` (`Codigo_Barras` ASC) VISIBLE,
  CONSTRAINT `FK1`
    FOREIGN KEY (`Cod_Zona`)
    REFERENCES `mydb`.`ZONAS` (`Cod_Zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK2`
    FOREIGN KEY (`Codigo_Barras`)
    REFERENCES `mydb`.`PRODUCTO` (`Codigo_Barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `DNI_Cliente` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Bonificacion` FLOAT NULL,
  `Metodo_Pago` VARCHAR(45) NULL,
  `Gasto_Mensual` FLOAT NULL,
  PRIMARY KEY (`DNI_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
  `Cod_Pedido` INT NOT NULL,
  `DNI_Cliente` VARCHAR(10) NULL,
  `Fecha` VARCHAR(45) NULL,
  `Importe` FLOAT NULL,
  `DNI_Empleado` VARCHAR(10) NULL,
  PRIMARY KEY (`Cod_Pedido`),
  INDEX `FK1_idx` (`DNI_Cliente` ASC) VISIBLE,
  INDEX `FK2_idx` (`DNI_Empleado` ASC) VISIBLE,
  CONSTRAINT `FK1`
    FOREIGN KEY (`DNI_Cliente`)
    REFERENCES `mydb`.`CLIENTE` (`DNI_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK2`
    FOREIGN KEY (`DNI_Empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`DNI_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO-PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO-PEDIDO` (
  `Codigo_Barras` INT NOT NULL,
  `Cod_Pedido` INT NOT NULL,
  PRIMARY KEY (`Codigo_Barras`, `Cod_Pedido`),
  INDEX `FK1_idx` (`Cod_Pedido` ASC) VISIBLE,
  CONSTRAINT `FK1`
    FOREIGN KEY (`Cod_Pedido`)
    REFERENCES `mydb`.`PEDIDO` (`Cod_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK2`
    FOREIGN KEY (`Codigo_Barras`)
    REFERENCES `mydb`.`PRODUCTO` (`Codigo_Barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
